import { Link } from 'react-router-dom'
import { Icon } from '../../components/ui/Icon'
import { products } from '../../data/products'
import { Journey } from '../home/Journey'

export function OriginsPage() { return <><section className="editorial-hero"><img src="/images/origin.webp" alt="Ripe coffee cherries on the branch" /><div><span className="eyebrow">It all begins somewhere</span><h1>A place.<br />A people.<br /><em>A coffee.</em></h1><p>We celebrate the places and the careful work behind every cup.</p></div></section><section className="origin-intro section-shell"><span className="eyebrow">A world worth tasting</span><h2>Different ground.<br /><em>Distinctive character.</em></h2><p>From Ethiopia’s fragrant highlands to Brazil’s sun-drenched plateaus, each origin has something of its own to say. We choose coffees for those differences, then roast to reveal them.</p></section><Journey /><section className="origin-list section-shell">{products.filter(p => p.category === 'Single origin' && p.id !== 'after-hours').map(p => <Link key={p.id} to={`/shop/${p.id}`}><span className="eyebrow">No. {p.edition}</span><h3>{p.origin}</h3><span>{p.region} · {p.altitude}</span><Icon name="arrow" size={24} /></Link>)}</section></> }

export function AboutPage() { return <><section className="about-intro section-shell"><span className="eyebrow">Independent spirit. Shared ritual.</span><h1>Life moves fast.<br /><em>Good coffee shouldn’t.</em></h1><div className="about-body"><p className="lead">ORREN is built around a simple idea: the everyday deserves a little more care.</p><div><p>We’re drawn to coffees with character. The kind that tell you something about the soil they grew in, the season they were picked, and the people who cared for them.</p><p>Our approach is simple. Start with something good. Treat it with respect. Share it while it’s fresh. No elaborate rituals required—just a little curiosity and a cup you love.</p></div></div></section><img className="about-photo" src="/images/hero-still-life.webp" alt="ORREN coffee and a ceramic cup in afternoon light" /><section className="about-values section-shell">{[['01', 'A sense of place.', 'Coffee should taste of where it comes from. We celebrate origin, variety, and processing, and make those details easy to explore.'], ['02', 'Care in the craft.', 'Small batches allow attention to the details. Our roasting direction favors sweetness, balance, and the distinct character of each coffee.'], ['03', 'Your daily moment.', 'The best coffee is the one you enjoy. We make it easy to find your flavor, learn something new, and build a ritual that fits your life.']].map(([number, title, text]) => <div key={number}><span className="eyebrow">{number}</span><h2>{title}</h2><p>{text}</p></div>)}</section><div className="about-cta section-shell"><h2>Make room for<br /><em>something good.</em></h2><Link to="/shop" className="button button-dark">Find your coffee <Icon name="arrow" /></Link></div></> }

const information: Record<string, {title: string; sections: [string, string][]}> = {
  shipping: { title: 'Good things, delivered.', sections: [['Shipping', 'This is a portfolio demonstration. The cart estimates $5 standard shipping, with free shipping on orders of $50 or more. No physical orders are shipped.'], ['Freshness & returns', 'For a production store, shipping regions, dispatch schedules, returns, and contact details must be configured with the actual merchant before accepting orders.'], ['Your order preview', 'The demo checkout creates a local order summary only. It does not collect payment or transmit your information.']] },
  privacy: { title: 'Your privacy matters.', sections: [['Stored on your device', 'ORREN saves bag contents in your browser’s local storage so they remain available when you return. Clearing your browser’s site data removes them.'], ['Forms and checkout', 'This portfolio demo has no server. Newsletter signups and checkout details are not transmitted. Checkout details are held in memory for the current visit only. Use example details when exploring the demo.'], ['External services', 'Fonts, product images, and site code are bundled locally. This app does not use advertising trackers, third-party analytics, or embedded social widgets.']] },
  terms: { title: 'A few simple terms.', sections: [['A fictional brand', 'ORREN is an original portfolio project. Product names, producers, availability, sourcing claims, and prices are fictional demonstration content, not representations of a trading company.'], ['No real transactions', 'The order experience is a frontend demonstration. No payment is requested, no purchase contract is formed, and no goods are dispatched.'], ['Photography', 'Original AI-generated product renderings and licensed editorial photographs are used. Attribution and asset details are recorded in the project documentation.']] },
  contact: { title: 'Start a conversation.', sections: [['About this experience', 'ORREN is a fictional coffee brand created to explore thoughtful commerce and interactive storytelling. This local preview does not operate a customer support service.'], ['Explore the collection', 'Looking for a balanced place to start? Try Huila. For a bright and floral cup, explore Sidama. For an easy espresso, meet First Light.'], ['Project enquiries', 'Use the portfolio owner’s contact details on the portfolio hosting this project. No messages are sent from this demonstration.']] },
}
export function InformationPage({ kind }: { kind: string }) { const content = information[kind]; return <section className="information-page section-shell"><span className="eyebrow">ORREN · Good to know</span><h1>{content.title}</h1><div>{content.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}</div><Link to="/shop" className="text-link">Back to the coffees <Icon name="right" /></Link></section> }
export function NotFoundPage() { return <section className="not-found section-shell"><span className="eyebrow">404 · A little off the path</span><h1>Let’s find you<br /><em>something good.</em></h1><Link to="/" className="button button-dark">Back to ORREN <Icon name="right" /></Link></section> }
