import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useCart } from './CartContext'
import { getProduct } from '../../data/products'
import { cartKey, money, priceForWeight } from '../../lib/commerce'
import { Icon } from '../../components/ui/Icon'

export default function CheckoutPage() {
  const { items, subtotal, clear } = useCart()
  const [order, setOrder] = useState<{ total: number; count: number; name: string } | null>(null)
  const shipping = subtotal >= 50 ? 0 : 5
  if (order) return <section className="checkout-success section-shell"><Icon name="check" size={44} /><span className="eyebrow">Your order preview is complete</span><h1>Here’s to a<br /><em>good morning, {order.name}.</em></h1><p>Your demo order contains {order.count} {order.count === 1 ? 'bag' : 'bags'} for {money(order.total)}.</p><p>No payment was taken. No order was sent. Your details were not stored or transmitted.</p><Link to="/shop" className="button button-dark">Keep exploring <Icon name="arrow" /></Link></section>
  if (!items.length) return <section className="not-found section-shell"><h1>Your next coffee<br /><em>is waiting.</em></h1><Link to="/shop" className="button button-dark">Explore the coffees <Icon name="arrow" /></Link></section>
  return <section className="checkout-page section-shell"><Link to="/shop" className="text-link">← Continue shopping</Link><h1>The next good <em>morning.</em></h1><div className="checkout-notice"><Icon name="coffee" /><p><strong>This is a demo checkout.</strong> Use example details to explore the experience. No payment is collected and no order will be placed.</p></div><div className="checkout-grid"><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); setOrder({ total: subtotal + shipping, count: items.reduce((n, item) => n + item.quantity, 0), name: String(data.get('firstName')).trim() || 'friend' }); clear(); window.scrollTo({ top: 0, behavior: 'instant' }) }}><h2>Your details</h2><label>Email address<input type="email" name="email" required autoComplete="email" placeholder="you@example.com" /></label><div className="form-row"><label>First name<input name="firstName" required maxLength={50} autoComplete="given-name" /></label><label>Last name<input name="lastName" required maxLength={50} autoComplete="family-name" /></label></div><label>Street address<input name="address" required autoComplete="street-address" /></label><div className="form-row"><label>City<input name="city" required autoComplete="address-level2" /></label><label>Postal code<input name="postalCode" required autoComplete="postal-code" /></label></div><label>Country<select name="country" required autoComplete="country-name"><option value="">Choose country</option><option>United States</option><option>United Kingdom</option><option>Saudi Arabia</option><option>United Arab Emirates</option><option>Canada</option><option>Germany</option><option>France</option><option>Australia</option></select></label><label className="checkbox-label"><input type="checkbox" required /> I understand this is a demonstration and no order will be sent.</label><button className="button button-dark" type="submit">Complete demo order <Icon name="right" /></button></form><aside className="checkout-summary"><h2>Good things in your bag</h2>{items.map(item => { const p = getProduct(item.productId)!; return <div className="checkout-line" key={cartKey(item)}><img src={p.image} alt={p.name} /><div><h3>{p.name}</h3><p>{item.weight}g · Qty {item.quantity}</p></div><span>{money(priceForWeight(p.price, item.weight) * item.quantity)}</span></div> })}<div className="checkout-totals"><div><span>Subtotal</span><span>{money(subtotal)}</span></div><div><span>Shipping</span><span>{shipping ? money(shipping) : 'On us'}</span></div><div><strong>Total</strong><strong>{money(subtotal + shipping)}</strong></div><small>USD · Demo prices include taxes.</small></div></aside></div></section>
}

